"""Atomic transaction group utilities and safety wrappers.

Purpose: Centralized atomic transaction composition, validation, and execution.
Provides single execution path for all AtomicTransactionComposer groups to ensure
uniform simulation-before-execute discipline and comprehensive logging.

Key Functions:
- AtomicGroupResult: Dataclass holding all atomic group metadata and results
- execute_with_simulation: Single execution path for all ATC groups (blocks execute without simulation)
- validate_atomic_group: Pre-submission validation of group structure, fees, and signer consistency
- estimate_group_fee: Universal fee calculator (outer_txn_count + inner_txn_count) * 1000 microALGO
- build_group_id: Stable identifier for log messages and audit trails
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional
import hashlib
import logging
import sqlite3
from algosdk.atomic_transaction_composer import AtomicTransactionComposer, SimulateAtomicTransactionResponse
from algosdk.v2client import algod
from algosdk import account as algo_account, transaction

from backend.utils.db import get_db_path
from backend.utils.flow_tracer import tracer

logger = logging.getLogger(__name__)


@dataclass
class AtomicGroupResult:
    """Complete result of an atomic transaction group execution.
    
    Attributes:
        group_id: SHA-256 hash (first 16 chars) of sorted transaction IDs - stable group identifier
        tx_ids: Transaction IDs in submission order (index 0 is first txn)
        confirmed_round: Block round where group was confirmed
        all_confirmed: True if all transactions have confirmed_round > 0
        simulation_passed: True if atc.simulate() succeeded before execute
        total_fee_paid_micro_algo: Sum of all fees actually paid (from simulation or confirmed round)
        context_description: Human-readable description (e.g., "x402_payment_with_escrow_release")
        created_at: ISO 8601 timestamp when group was submitted
    
    Purpose:
        Provides complete audit trail and proof that atomic group executed as intended.
        group_id enables deduplication and idempotency checking across restarts.
    """
    group_id: str
    tx_ids: list[str]
    confirmed_round: int
    all_confirmed: bool
    simulation_passed: bool
    total_fee_paid_micro_algo: int
    context_description: str
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


class TransactionSimulationError(Exception):
    """Raised when atomic transaction group simulation fails.
    
    Attributes:
        message: Human-readable error description
        simulation_trace: Full SimulateAtomicTransactionResponse for debugging
    """
    def __init__(self, message: str, simulation_trace: Optional[SimulateAtomicTransactionResponse] = None):
        super().__init__(message)
        self.message = message
        self.simulation_trace = simulation_trace


def estimate_group_fee(outer_tx_count: int, inner_tx_count: int) -> int:
    """Calculate minimum atomic transaction group fee.
    
    Formula: (outer_txn_count + inner_txn_count) * 1000 microALGO
    - Each transaction (outer or inner) costs 1000 microALGO base fee
    - Outer group transactions have one fee that covers all inner transactions they generate
    
    Args:
        outer_tx_count: Number of transactions at outer (group) level
        inner_tx_count: Total inner transactions generated by all outer txns
    
    Returns:
        Minimum fee in microALGO to cover all transactions
    
    Examples:
        estimate_group_fee(2, 0) -> 2000 (2 outer txns, no inner txns)
        estimate_group_fee(1, 4) -> 5000 (1 outer txn that generates 4 inner)
        estimate_group_fee(2, 2) -> 4000 (2 outer txns, 2 total inner)
    """
    return (outer_tx_count + inner_tx_count) * 1000


def build_group_id(tx_ids: list[str]) -> str:
    """Build stable identifier for atomic transaction group.
    
    Uses sorted transaction IDs (eliminates order dependency) and takes first 16 chars
    of SHA-256 hash for human-readable logs while maintaining collision resistance.
    
    Args:
        tx_ids: List of transaction IDs in group
    
    Returns:
        16-character hex string identifier
    
    Purpose:
        Enables log deduplication, idempotency checks, and audit trail queries.
    
    Example:
        build_group_id(["txn1", "txn2"]) -> "a1b2c3d4e5f6g7h8"
    """
    sorted_txns = "".join(sorted(tx_ids))
    full_hash = hashlib.sha256(sorted_txns.encode()).hexdigest()
    return full_hash[:16]


def validate_atomic_group(
    transactions: list[transaction.Transaction],
    signers: list,
    inner_tx_count: int = 0,
) -> tuple[bool, str]:
    """Validate atomic transaction group before submission.
    
    Checks five critical conditions:
    1. Group size: between 2 and 16 transactions (AVM enforces 16 max)
    2. Network consistency: all transactions use same genesis_hash (no MainNet/TestNet mixing)
    3. Fee sufficiency: total fees >= (1 + num_inner_txns) * 1000 microALGO
    4. Signer consistency: all signers match sender addresses of their transactions
    5. No double-submission: transaction IDs not already in api_request_log (if client provided)
    
    Args:
        transactions: List of Transaction objects to validate
        signers: List of TransactionSigner objects (must match transaction order)
        inner_tx_count: Expected number of inner transactions generated by this group
    
    Returns:
        (True, "") if all checks pass
        (False, specific_failure_reason_string) if any check fails
    
    Purpose:
        Early failure detection prevents broadcasting malformed groups that would fail
        on-chain and waste fees. Enables defensive programming with specific error messages.
    """
    # Check 1: Group size
    if len(transactions) < 2:
        return False, "Atomic group must have at least 2 transactions"
    if len(transactions) > 16:
        return False, f"Atomic group exceeds maximum of 16 transactions (has {len(transactions)})"
    
    # Check 2: Network consistency
    if len(set(tx.get_txn_dict().get("gh") for tx in transactions)) > 1:
        return False, "All transactions must use same genesis_hash (prevent MainNet/TestNet mixing)"
    
    # Check 3: Fee sufficiency
    total_fee = sum(tx.fee for tx in transactions)
    min_fee = estimate_group_fee(len(transactions), max(inner_tx_count, 0))
    if total_fee < min_fee:
        return False, f"Total fee {total_fee} microALGO is below minimum {min_fee}"
    
    # Check 4: Signer consistency
    if len(signers) != len(transactions):
        return False, f"Signer count {len(signers)} does not match transaction count {len(transactions)}"

    for idx, (txn, signer) in enumerate(zip(transactions, signers, strict=True)):
        sender = getattr(txn, "sender", "")
        private_key = getattr(signer, "private_key", None)
        if isinstance(private_key, str) and private_key:
            try:
                signer_address = algo_account.address_from_private_key(private_key)
            except Exception as exc:
                return False, f"Signer at index {idx} has invalid private key: {exc}"
            if signer_address != sender:
                return False, (
                    f"Signer mismatch at index {idx}: txn sender {sender} "
                    f"does not match signer address {signer_address}"
                )

    # Check 5: Guard against accidental re-submission by checking known request logs.
    try:
        tx_ids = [txn.get_txid() for txn in transactions]
        db_path = get_db_path()
        with sqlite3.connect(db_path) as conn:
            for tx_id in tx_ids:
                row = conn.execute(
                    """
                    SELECT request_id
                    FROM api_request_log
                    WHERE request_id = ?
                       OR request_body_summary LIKE ?
                    LIMIT 1
                    """,
                    (tx_id, f"%{tx_id}%"),
                ).fetchone()
                if row is not None:
                    return False, f"Transaction {tx_id} appears to have already been submitted"
    except Exception as exc:
        logger.debug("Skipped duplicate-submission check due to DB issue: %s", exc)
    
    return True, ""


async def execute_with_simulation(
    atc: AtomicTransactionComposer,
    algod_client: algod.AlgodClient,
    context_description: str,
) -> AtomicGroupResult:
    """Execute atomic transaction group with mandatory pre-execution simulation.
    
    This is the ONLY place in the codebase where atc.execute() is called.
    All ATC groups must flow through this function to ensure uniform safety checks.
    
    Process:
    1. Call atc.simulate() for dry-run safety check
    2. If simulation fails, log full trace and raise TransactionSimulationError (never execute)
    3. If simulation succeeds, extract fee usage and warn if dangerously close to limit
    4. Call atc.execute() for real submission
    5. Record in FlowTracer and return complete result
    
    Args:
        atc: AtomicTransactionComposer with all transactions added and ready to execute
        algod_client: AlgodClient for network interaction
        context_description: Human-readable description (e.g., "x402_payment_with_escrow")
    
    Returns:
        AtomicGroupResult with all transaction IDs, confirmed round, and metadata
    
    Raises:
        TransactionSimulationError: If simulation fails (with full simulation trace for debugging)
    
    Guarantees:
        - Simulation always runs before execute
        - Full simulation trace logged if simulation fails
        - Fee estimate warnings logged if dangerously close to limit
        - All execution events recorded in FlowTracer
        - atc.execute() is never called after a failed simulation
    
    Purpose:
        Prevents silent failures and fee-too-low errors by catching problems in simulation.
        Provides complete audit trail via logging for all atomic operations.
    """
    logger.info("Simulating atomic group: %s", context_description)
    
    # Simulate BEFORE execute
    try:
        sim_result = atc.simulate(algod_client)
    except Exception as exc:
        logger.error("Simulation setup failed for %s: %s", context_description, exc, exc_info=True)
        raise TransactionSimulationError(
            message=f"Simulation setup failed: {str(exc)}",
            simulation_trace=None,
        ) from exc
    
    # Check simulation success
    failed_at = getattr(sim_result, "failed_at", None)
    failure_message = getattr(sim_result, "failure_message", "")
    if failure_message or failed_at:
        logger.error("Simulation failed for %s: %s", context_description, failure_message)
        logger.debug("Full simulation trace for %s: %s", context_description, sim_result.simulate_response)
        tracer.record(
            "payment.simulation_failed",
            "failure",
            plain_english_description=f"Simulation failed for {context_description}: {failure_message}",
            error_code="SIMULATION_FAILED",
            error_message=str(failure_message),
            metadata={"failed_at": failed_at},
        )
        
        raise TransactionSimulationError(
            message=f"Simulation failed for {context_description}: {failure_message}",
            simulation_trace=sim_result,
        )
    
    tracer.record(
        "payment.simulation_passed",
        "success",
        plain_english_description=f"Simulation passed for {context_description}",
    )

    # Simulation passed - extract fee usage and warn if dangerous
    eval_overview = sim_result.simulate_response.get("txn-groups", [])
    simulated_required_fee = 0
    if eval_overview and isinstance(eval_overview, list):
        first_group = eval_overview[0] if eval_overview else {}
        if isinstance(first_group, dict):
            group_fee = first_group.get("group-fee")
            if isinstance(group_fee, int):
                simulated_required_fee = group_fee
    configured_fee = sum(getattr(txn_with_signer.txn, "fee", 0) for txn_with_signer in atc.txn_list)
    if simulated_required_fee > 0 and configured_fee > 0:
        if simulated_required_fee > configured_fee * 1.10:
            logger.warning(
                "Simulated fee for %s exceeds configured fee by >10%% (configured=%s required=%s)",
                context_description,
                configured_fee,
                simulated_required_fee,
            )
    
    # Execute the atomic group
    logger.info("Broadcasting atomic group: %s", context_description)
    
    try:
        result = atc.execute(algod_client, wait_rounds=4)
    except Exception as exc:
        logger.error("Execution failed for %s: %s", context_description, exc, exc_info=True)
        tracer.record(
            "payment.broadcast_failed",
            "failure",
            plain_english_description=f"Broadcast failed for {context_description}",
            error_code="BROADCAST_FAILED",
            error_message=str(exc),
        )
        raise
    
    # Build result
    group_id = build_group_id(result.tx_ids)
    total_fee = sum(atc.txn_list[i].txn.fee for i in range(len(result.tx_ids)))
    
    atomic_result = AtomicGroupResult(
        group_id=group_id,
        tx_ids=result.tx_ids,
        confirmed_round=result.confirmed_round,
        all_confirmed=all(result.confirmed_round > 0 for _ in result.tx_ids),
        simulation_passed=True,
        total_fee_paid_micro_algo=total_fee,
        context_description=context_description,
    )
    
    tracer.record(
        "payment.broadcast_completed",
        "success",
        tx_id=result.tx_ids[0] if result.tx_ids else None,
        plain_english_description=f"Group submitted: {context_description}",
        metadata={"group_id": group_id, "tx_ids": result.tx_ids},
    )
    logger.info(
        "Atomic group completed: %s | group_id=%s confirmed_round=%s",
        context_description,
        group_id,
        result.confirmed_round,
    )
    
    return atomic_result
